<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite-Booking" duration-ms="97" started-at="2020-07-26T10:52:42Z" finished-at="2020-07-26T10:52:42Z">
    <groups>
      <group name="confirm">
        <method signature="Booking.confirm()[pri:0, instance:note.Booking@e45f292]" name="confirm" class="note.Booking"/>
      </group> <!-- confirm -->
      <group name="search">
        <method signature="Booking.search()[pri:0, instance:note.Booking@e45f292]" name="search" class="note.Booking"/>
      </group> <!-- search -->
      <group name="select">
        <method signature="Booking.select()[pri:0, instance:note.Booking@e45f292]" name="select" class="note.Booking"/>
      </group> <!-- select -->
      <group name="sanity">
        <method signature="Booking.search()[pri:0, instance:note.Booking@e45f292]" name="search" class="note.Booking"/>
        <method signature="Booking.select()[pri:0, instance:note.Booking@e45f292]" name="select" class="note.Booking"/>
        <method signature="Booking.checkout()[pri:0, instance:note.Booking@e45f292]" name="checkout" class="note.Booking"/>
        <method signature="Booking.confirm()[pri:0, instance:note.Booking@e45f292]" name="confirm" class="note.Booking"/>
      </group> <!-- sanity -->
      <group name="checkout">
        <method signature="Booking.checkout()[pri:0, instance:note.Booking@e45f292]" name="checkout" class="note.Booking"/>
      </group> <!-- checkout -->
    </groups>
    <test name="Booking" duration-ms="97" started-at="2020-07-26T10:52:42Z" finished-at="2020-07-26T10:52:42Z">
      <class name="note.Booking">
        <test-method status="FAIL" signature="search()[pri:0, instance:note.Booking@e45f292]" name="search" duration-ms="15" started-at="2020-07-26T10:52:42Z" finished-at="2020-07-26T10:52:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at note.Booking.search(Booking.java:10)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- search -->
        <test-method status="SKIP" signature="select()[pri:0, instance:note.Booking@e45f292]" name="select" duration-ms="0" depends-on-groups="search" started-at="2020-07-26T10:52:42Z" finished-at="2020-07-26T10:52:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Booking.select()[pri:0, instance:note.Booking@e45f292] depends on not successfully finished methods in group "search"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Booking.select()[pri:0, instance:note.Booking@e45f292] depends on not successfully finished methods in group "search"
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- select -->
        <test-method status="SKIP" signature="checkout()[pri:0, instance:note.Booking@e45f292]" name="checkout" duration-ms="0" depends-on-groups="select" started-at="2020-07-26T10:52:42Z" finished-at="2020-07-26T10:52:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Booking.checkout()[pri:0, instance:note.Booking@e45f292] depends on not successfully finished methods in group "select"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Booking.checkout()[pri:0, instance:note.Booking@e45f292] depends on not successfully finished methods in group "select"
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkout -->
        <test-method status="SKIP" signature="confirm()[pri:0, instance:note.Booking@e45f292]" name="confirm" duration-ms="0" depends-on-groups="checkout" started-at="2020-07-26T10:52:42Z" finished-at="2020-07-26T10:52:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Booking.confirm()[pri:0, instance:note.Booking@e45f292] depends on not successfully finished methods in group "checkout"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Booking.confirm()[pri:0, instance:note.Booking@e45f292] depends on not successfully finished methods in group "checkout"
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirm -->
      </class> <!-- note.Booking -->
    </test> <!-- Booking -->
  </suite> <!-- Suite-Booking -->
</testng-results>
